spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maleyiyo/config-repo
          username: maleyiyo
          password: ly741900@9310
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev
label:
  release
