spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://172.20.10.3:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 172.20.10.3
    port: 5672
    password: guest
    username: guest
  redis:
    host: 172.20.10.3
    port: 6379
  jpa:
    show-sql: true
