spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    password: guest
    username: guest
  redis:
    host: 192.168.99.100
    port: 6379
ribbon:
  eureka:
    enabled: true
